name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker
        run: echo "${{ secrets.PASSWORD }}" | docker login -u "${{ secrets.USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.USERNAME }}/helloworld
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker push $IMAGE_NAME:${{ github.sha }}
          echo "Image pushed: $IMAGE_NAME:${{ github.sha }}"
